# Site settings
title: cosmicac
baseurl: "/cosmicac.github.io"
url: "http://cosmicac.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
