# Site settings
title: cosmicac
baseurl: "/home"
url: "http://cosmicac.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 

#header links
header-links:
  github: cosmicac
  linkedin: li-tom
  email: weirdotomli@gmail.com

